### ISSUE TITLE
File.open w is throwing an error in Ruby 3.1.4

### ISSUE THREAD

**Issue by walterdavis** [actsasflinn/typst-rb#1]
https://github.com/actsasflinn/typst-rb/blob/main/lib/typst.rb#L20 is causing me grief while using this library inside a Rails project. Changing that line to use 'wb' instead of 'w' solved the problem for me, but I'm not sure if the real cause was elsewhere.

I forked the library during my testing, so I could send a MR if you're interested.

**Comment by actsasflinn** [comment]
Thanks for the issue and solution. Fix committed and new gem published.
